FROM mysql
MAINTAINER amarnath

RUN chown -R mysql:root /var/lib/mysql/

ENV MYSQL_DATABASE ingdb
ENV MYSQL_USER inguser1
ENV MYSQL_PASSWORD H@ckath0n
ENV MYSQL_ROOT_PASSWORD H@ckath0n
ENV MYSQL_PORT=3306

EXPOSE 3306

